### ISSUE TITLE
Игнорирует нажатия

### ISSUE THREAD

**Issue by TheSt1G** [AntonMason/whatLexxxa#1]
Во время движения мыши клик не засчитывается. Пробовал перезапустить браузер, компьютер, другой браузер, операционную систему и даже модем! Проверил на вирусы, почистил реестр, дефрагментировал диск и переустановил драйвера, ничего не помогает!

**Comment by AntonMason** [comment]
Исправлено в beta 1.1. Спасибо за отзыв)
